from __future__ import annotations

ENCODING = "utf-8"

MAX_CONNECTIONS = 2
IDLE_CONNECTION_TIMEOUT = 10.0
BLOCKING_TIMEOUT = 5.0
PURGE_UNHEALTHY_NODES = False

CONNECT_TIMEOUT = 1.0
READ_TIMEOUT = None
MAX_INFLIGHT_REQUESTS_PER_CONNECTION = 100
